
$(document).ready(function(){var key=0;var wraHeight=null;var timer=null;var wraHeight=$(window).height();$('#wrapper').height(wraHeight);$('#circle').css('top',(wraHeight/2)-$('#circle').height()/2);$(window).resize(function(){var wraHeight=$(window).height();$('#wrapper').height(wraHeight);$('#circle').css('top',(wraHeight/2)-$('#circle').height()/2);})
$('.page').eq(key).removeClass('out').siblings().addClass('out');$(document).mousewheel(function(event,d){clearTimeout(timer);timer=setTimeout(function(){if(d==-1){key++;if(key>4){key=4;}}else{key--;if(key<0){key=0;}}
$('#wrapper').attr('class','go'+key+'');$('#circle li').eq(key).addClass('current').siblings().removeClass('current');$('.top-r .nav a').eq(key).addClass('current').siblings().removeClass('current');$('.page').eq(key).removeClass('out').siblings().addClass('out');},200)})
$('#circle li').click(function(){$(this).addClass('current').siblings().removeClass('current');$('#wrapper').attr('class','go'+$(this).index()+'');$('.top-r .nav a').eq($(this).index()).addClass('current').siblings().removeClass('current');$('.page').eq($(this).index()).removeClass('out').siblings().addClass('out');});$('.top-r .nav a').click(function(){$(this).addClass('current').siblings().removeClass('current');$('#wrapper').attr('class','go'+$(this).index()+'');$('#circle li').eq($(this).index()).addClass('current').siblings().removeClass('current');$('.page').eq($(this).index()).removeClass('out').siblings().addClass('out');})
/*$('.top-r .nav a').hover(function(){$(this).addClass('current').siblings().removeClass('current');});*/$('.top-r-menut').click(function(){var a_len=$('.nav a').length;var a_wid=a_len*108;if($(this).hasClass('a-hide')){$(this).removeClass('a-hide');$('.top-r-menu').stop().show(function(){$(this).animate({'width':97},200)});$('.top-r .nav').stop().animate({'width':0},200);$('.top-r .navbox').stop().animate({'width':0},200);}else{$(this).addClass('a-hide');$('.top-r-menu').stop().animate({'width':0},200,function(){$(this).hide();});$('.top-r .nav').stop().animate({'width':a_wid},200);$('.top-r .navbox').stop().animate({'width':a_wid},200);}});$('.two li').hover(function(){$(this).addClass('current');},function(){$(this).removeClass('current');})
$('.three .right .icon01 li').each(function(index,element){$(element).css('transition-delay',0.025*index+'s');})
var $number01=0;var $number02=0;var $number03=0;var timer05=null;var timer07=null;var timer08=null;timer05=setInterval(appfun01,2000);timer07=setInterval(appfun02,2000);timer08=setInterval(appfun03,2000);$('.right01').click(function(event){appfun01();});$('.right02').click(function(event){appfun02();});$('.right03').click(function(event){appfun03();});$('.left01').click(function(event){$number01--;if($number01<0){$number01=4;$(".appzhuti .ulplay01").css('left',-1280);}
$(".appzhuti .ulplay01").stop().animate({"left":-$number01*256},800);});$('.left02').click(function(event){$number02--;if($number02<0){$number02=4;$(".appzhuti .ulplay02").css('left',-1280);}
$(".appzhuti .ulplay02").stop().animate({"left":-$number02*256},800);});$('.left03').click(function(event){$number03--;if($number03<0){$number03=4;$(".appzhuti .ulplay03").css('left',-1280);}
$(".appzhuti .ulplay03").stop().animate({"left":-$number03*256},800);});function appfun01(){$number01++;if($number01>5){$number01=1;$(".appzhuti .ulplay01").css('left',0);}
$(".appzhuti .ulplay01").stop().animate({"left":-$number01*256},800);}
function appfun02(){$number02++;if($number02>5){$number02=1;$(".appzhuti .ulplay02").css('left',0);}
$(".appzhuti .ulplay02").stop().animate({"left":-$number02*256},800);}
function appfun03(){$number03++;if($number03>5){$number03=1;$(".appzhuti .ulplay03").css('left',0);}
$(".appzhuti .ulplay03").stop().animate({"left":-$number03*256},800);}
$(".appzhuti01").hover(function(){clearInterval(timer05);},function(){timer05=setInterval(appfun01,2000);});$(".appzhuti02").hover(function(){clearInterval(timer07);},function(){timer07=setInterval(appfun02,2000);});$(".appzhuti03").hover(function(){clearInterval(timer08);},function(){timer08=setInterval(appfun03,2000);});$('.three .appzhuti').hover(function(){$(this).addClass('current');},function(){$(this).removeClass('current');});$('.four .tit li').click(function(){$(this).addClass('current').siblings().removeClass('current');$('.four .webshow').children('li').eq($(this).index()).addClass('current').siblings().removeClass('current');});});